backend:
  name: github
  repo: clevinson/testing-ncms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: album-art, label: Album Art, widget: image}
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
